// src/common/enums.ts

export enum UserRole {
  PASSENGER = 'PASSENGER',
  DRIVER = 'DRIVER',
}

export enum PoolStatus {
  OPEN = 'OPEN',
  LOCKED = 'LOCKED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum RideRequestStatus {
  REQUESTED = 'REQUESTED',
  MATCHED = 'MATCHED',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}


export enum DhakaZone {
  BANANI = 'BANANI',
  GULSHAN = 'GULSHAN',
  MOHAKHALI = 'MOHAKHALI',
  DHANMONDI = 'DHANMONDI',
  MIRPUR = 'MIRPUR',
  UTTARA = 'UTTARA',
  FARMGATE = 'FARMGATE',
  BASHUNDHARA = 'BASHUNDHARA',
}